services:
  apd.database:
    image: postgres:latest
    container_name: apd.database
    environment:
      - POSTGRES_DB=adp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/apd-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  apd.api:
    image: apd.api
    container_name: apd.api
    build:
      context: .
      dockerfile: Apd.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      apd.database:
        condition: service_healthy
        
  apd.front:
    image: apd.front
    container_name: apd.front
    build:
      context: ./Frontend/test-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      apd.api:
        condition: service_started
