# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  apd.api:
    build:
      context: "/Users/karolzebala/RiderProjects/Apd"
      dockerfile: "Apd.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "apd.api:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "/Users/karolzebala/RiderProjects/Apd/Apd.Api:/app:rw"
    - "/Users/karolzebala/RiderProjects/Apd:/src:rw"
    - "/Users/karolzebala/.microsoft/usersecrets:/root/.microsoft/usersecrets"
    - "/Users/karolzebala/.nuget/packages:/root/.nuget/packages"
    - "/Users/karolzebala/.local/share/JetBrains/RiderRemoteDebugger/2024.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/karolzebala/Library/Logs/JetBrains/Rider2024.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_2_01_10_12_07:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  apd.migrations:
    build:
      context: "/Users/karolzebala/RiderProjects/Apd"
      dockerfile: "Apd.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Apd.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "apd.api:dev"
    ports: []
    volumes:
    - "/Users/karolzebala/RiderProjects/Apd/Apd.Api:/app:rw"
    - "/Users/karolzebala/RiderProjects/Apd:/src:rw"
    - "/Users/karolzebala/.microsoft/usersecrets:/root/.microsoft/usersecrets"
    - "/Users/karolzebala/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
